### ISSUE TITLE
Loss of requests when HAProxy is reloaded

### ISSUE THREAD

**Issue by ema-pe** [unimib-datAI/dfaas#8]
When the DFaaS agent recalculates the weights and updates the HAProxy configuration by reloading HAProxy (the actual command is shown below from the `stecattaneo-dev` branch), the open connections will be closed and new requests will be rejected until HAProxy is fully reloaded.

https://github.com/unimib-datAI/dfaas/blob/de1f6fb88dc836f4f0dce1b856c7760a2207936e/dfaasagent.env#L23

You can see this in the plots of requests and cumulative errors (this example is the figlet-light-350 test with the node margin strategy using the container environment): the small spikes occur when HAProxy is reloaded.

![plot-nodes-responses-and-cumulatives](https://github.com/user-attachments/assets/9beab0f0-3eed-4ccf-83fd-6d3433c61a42)

One solution may be to rewrite how HAProxy is reloaded, taking advantage of the HAProxy hitless reload feature (starting from 1.8 version). More info here: https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto

**Comment by ema-pe** [comment]
I built and started a local node (only one node) and ran some tests with vegeta. The result is the same as in the previous message: there is a drop in requests when haproxy is restarted (in red):

![Screenshot_2024-11-19_16-05-06](https://github.com/user-attachments/assets/b6b6cb4b-91ef-4eae-bc1d-fe8ee247aeb4)

These are some partial logs when haproxy is restarted:

```
Nov 19 14:57:00 dfaas-next haproxy[34278]: <134>Nov 19 14:57:00 haproxy[34278]: 127.0.0.1:50071 [19/Nov/2024:14:57:00.061] fe_main be_figlet/127.0.0.1 0/0/1/15/16 200>
Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : haproxy version is 2.8.5-1ubuntu3.1
Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : path to executable is /usr/sbin/haproxy
Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : Exiting Master process...
Nov 19 14:57:00 dfaas-next systemd[1]: Stopping haproxy.service - HAProxy Load Balancer...
Nov 19 14:57:00 dfaas-next haproxy[34274]: [ALERT]    (34274) : Current worker (34278) exited with code 143 (Terminated)
Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : All workers exited. Exiting... (0)
Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Deactivated successfully.
Nov 19 14:57:00 dfaas-next systemd[1]: Stopped haproxy.service - HAProxy Load Balancer.
Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Consumed 1.882s CPU time.
Nov 19 14:57:00 dfaas-next systemd[1]: Starting haproxy.service - HAProxy Load Balancer...
Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : haproxy version is 2.8.5-1ubuntu3.1
Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : path to executable is /usr/sbin/haproxy
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:70] : a 'http-request' rule placed after a 'use_backend' ru>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:71] : a 'http-request' rule placed after a 'use_backend' ru>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:72] : a 'http-request' rule placed after a 'use_backend' ru>
Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : New worker (37281) forked
Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : Loading success.
Nov 19 14:57:00 dfaas-next systemd[1]: Started haproxy.service - HAProxy Load Balancer.
Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:40193 [19/Nov/2024:14:57:00.260] fe_main be_figlet/127.0.0.1 0/0/0/15/15 200>
Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:37601 
```

**Comment by aletundo** [comment]
> I built and started a local node (only one node) and ran some tests with vegeta. The result is the same as in the previous message: there is a drop in requests when haproxy is restarted (in red):
> 
> ![Screenshot_2024-11-19_16-05-06](https://private-user-images.githubusercontent.com/21246809/387710925-b6b6cb4b-91ef-4eae-bc1d-fe8ee247aeb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzIxMTAsIm5iZiI6MTczMjAzMTgxMCwicGF0aCI6Ii8yMTI0NjgwOS8zODc3MTA5MjUtYjZiNmNiNGItOTFlZi00ZWFlLWJjMWQtZmU4ZWUyNDdhZWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYzhhZjlkMDQzMjA1ZjYwNmEyZWFhOWRkNWUwNDBlMzk3ODdiNzFkNmI5YWQ3YTZlNDc1NDkzYjcwOWE1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wilsqccoveEZkE8VJWq_4HvhSuJWbEUR7VfobArmMiw)
> 
> These are some partial logs when haproxy is restarted:
> 
> ```
> Nov 19 14:57:00 dfaas-next haproxy[34278]: <134>Nov 19 14:57:00 haproxy[34278]: 127.0.0.1:50071 [19/Nov/2024:14:57:00.061] fe_main be_figlet/127.0.0.1 0/0/1/15/16 200>
> Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : haproxy version is 2.8.5-1ubuntu3.1
> Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : path to executable is /usr/sbin/haproxy
> Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : Exiting Master process...
> Nov 19 14:57:00 dfaas-next systemd[1]: Stopping haproxy.service - HAProxy Load Balancer...
> Nov 19 14:57:00 dfaas-next haproxy[34274]: [ALERT]    (34274) : Current worker (34278) exited with code 143 (Terminated)
> Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : All workers exited. Exiting... (0)
> Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Deactivated successfully.
> Nov 19 14:57:00 dfaas-next systemd[1]: Stopped haproxy.service - HAProxy Load Balancer.
> Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Consumed 1.882s CPU time.
> Nov 19 14:57:00 dfaas-next systemd[1]: Starting haproxy.service - HAProxy Load Balancer...
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : haproxy version is 2.8.5-1ubuntu3.1
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : path to executable is /usr/sbin/haproxy
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:70] : a 'http-request' rule placed after a 'use_backend' ru>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:71] : a 'http-request' rule placed after a 'use_backend' ru>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:72] : a 'http-request' rule placed after a 'use_backend' ru>
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : New worker (37281) forked
> Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : Loading success.
> Nov 19 14:57:00 dfaas-next systemd[1]: Started haproxy.service - HAProxy Load Balancer.
> Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:40193 [19/Nov/2024:14:57:00.260] fe_main be_figlet/127.0.0.1 0/0/0/15/15 200>
> Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:37601 
> ```

Do you mean that even using the hitless reload it stills drops?

**Comment by ema-pe** [comment]
> > I built and started a local node (only one node) and ran some tests with vegeta. The result is the same as in the previous message: there is a drop in requests when haproxy is restarted (in red):
> > ![Screenshot_2024-11-19_16-05-06](https://private-user-images.githubusercontent.com/21246809/387710925-b6b6cb4b-91ef-4eae-bc1d-fe8ee247aeb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzIxMTAsIm5iZiI6MTczMjAzMTgxMCwicGF0aCI6Ii8yMTI0NjgwOS8zODc3MTA5MjUtYjZiNmNiNGItOTFlZi00ZWFlLWJjMWQtZmU4ZWUyNDdhZWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYzhhZjlkMDQzMjA1ZjYwNmEyZWFhOWRkNWUwNDBlMzk3ODdiNzFkNmI5YWQ3YTZlNDc1NDkzYjcwOWE1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wilsqccoveEZkE8VJWq_4HvhSuJWbEUR7VfobArmMiw)
> > These are some partial logs when haproxy is restarted:
> > ```
> > Nov 19 14:57:00 dfaas-next haproxy[34278]: <134>Nov 19 14:57:00 haproxy[34278]: 127.0.0.1:50071 [19/Nov/2024:14:57:00.061] fe_main be_figlet/127.0.0.1 0/0/1/15/16 200>
> > Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : haproxy version is 2.8.5-1ubuntu3.1
> > Nov 19 14:57:00 dfaas-next haproxy[34274]: [NOTICE]   (34274) : path to executable is /usr/sbin/haproxy
> > Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : Exiting Master process...
> > Nov 19 14:57:00 dfaas-next systemd[1]: Stopping haproxy.service - HAProxy Load Balancer...
> > Nov 19 14:57:00 dfaas-next haproxy[34274]: [ALERT]    (34274) : Current worker (34278) exited with code 143 (Terminated)
> > Nov 19 14:57:00 dfaas-next haproxy[34274]: [WARNING]  (34274) : All workers exited. Exiting... (0)
> > Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Deactivated successfully.
> > Nov 19 14:57:00 dfaas-next systemd[1]: Stopped haproxy.service - HAProxy Load Balancer.
> > Nov 19 14:57:00 dfaas-next systemd[1]: haproxy.service: Consumed 1.882s CPU time.
> > Nov 19 14:57:00 dfaas-next systemd[1]: Starting haproxy.service - HAProxy Load Balancer...
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : haproxy version is 2.8.5-1ubuntu3.1
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : path to executable is /usr/sbin/haproxy
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : unexpected character '0' after the timer value '1m0s', only (us=microseconds,ms=milliseconds,>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:70] : a 'http-request' rule placed after a 'use_backend' ru>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:71] : a 'http-request' rule placed after a 'use_backend' ru>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [WARNING]  (37279) : config : parsing [/etc/haproxy/haproxy.cfg:72] : a 'http-request' rule placed after a 'use_backend' ru>
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : New worker (37281) forked
> > Nov 19 14:57:00 dfaas-next haproxy[37279]: [NOTICE]   (37279) : Loading success.
> > Nov 19 14:57:00 dfaas-next systemd[1]: Started haproxy.service - HAProxy Load Balancer.
> > Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:40193 [19/Nov/2024:14:57:00.260] fe_main be_figlet/127.0.0.1 0/0/0/15/15 200>
> > Nov 19 14:57:00 dfaas-next haproxy[37281]: <134>Nov 19 14:57:00 haproxy[37281]: 127.0.0.1:37601 
> > ```
> 
> Do you mean that even using the hitless reload it stills drops?

No. The test was performed without touching HAProxy and the agent. Hitless reload is disabled by default in HAProxy. In the next few days I'll try to enable it and do some comparisons, I expect the dropped requests to disappear.

**Comment by ema-pe** [comment]
After reading the HAProxy documentation, I think the problem can be summed up in two points:

1. When the agent runs `systemctl restart haproxy`, HAProxy performs a hard stop, immediately closing all open connections.
2. We can change this to `systemd reload haproxy`: since HAProxy is configured in master-worker mode in Ubuntu, using `reload` instead of `restart` will cause HAProxy to gracefully stop (the hitless reload feature) and wait for open connections to close. There's no need to change the configuration (according to the [official article](https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto)), because the master-worker node does this automatically.

I found this information about reloading HAProxy in the [official documentation](https://docs.haproxy.org/2.8/management.html#4).

This is for reference the default unit file for HAProxy 2.8.5 on Ubuntu 24.04.1:

<details>
<summary>/usr/lib/systemd/system/haproxy.service</summary>

```
[Unit]
Description=HAProxy Load Balancer
Documentation=man:haproxy(1)
Documentation=file:/usr/share/doc/haproxy/configuration.txt.gz
After=network-online.target rsyslog.service
Wants=network-online.target

[Service]
EnvironmentFile=-/etc/default/haproxy
EnvironmentFile=-/etc/sysconfig/haproxy
BindReadOnlyPaths=/dev/log:/var/lib/haproxy/dev/log
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid" "EXTRAOPTS=-S /run/haproxy-master.sock"
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
ExecReload=/usr/sbin/haproxy -Ws -f $CONFIG -c -q $EXTRAOPTS
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
SuccessExitStatus=143
Type=notify

# The following lines leverage SystemD's sandboxing options to provide
# defense in depth protection at the expense of restricting some flexibility
# in your setup (e.g. placement of your configuration files) or possibly
# reduced performance. See systemd.service(5) and systemd.exec(5) for further
# information.

# NoNewPrivileges=true
# ProtectHome=true
# If you want to use 'ProtectSystem=strict' you should whitelist the PIDFILE,
# any state files and any other files written using 'ReadWritePaths' or
# 'RuntimeDirectory'.
# ProtectSystem=true
# ProtectKernelTunables=true
# ProtectKernelModules=true
# ProtectControlGroups=true
# If your SystemD version supports them, you can add: @reboot, @swap, @sync
# SystemCallFilter=~@cpu-emulation @keyring @module @obsolete @raw-io

[Install]
WantedBy=multi-user.target
```
</details>

**Comment by ema-pe** [comment]
After changing `restart` to `reload` (see #22), I did a test with a single node and this is the result:

![Screenshot_2024-11-21_11-17-02](https://github.com/user-attachments/assets/22b8ea4c-8812-4ecf-b485-83de1e0e491d)

There are no errors, no connections are dropped when HAProxy is restarted.
